# Generated by Django 5.0.2 on 2024-05-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_stockelement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockelement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
