
### POST request to example server
POST http://localhost:8000/api/token/refresh/

### POST request to get Token
POST http://localhost:8000/api/token/

### POST request to send Email
POST http://localhost:8000/api/send/

### GET request to get Token
GET http://localhost:8000/api/token/

### POST request to register an user in the database
POST http://localhost:8000/api/auth/register/
content-type: application/json

{
    "username":"Valerie",
    "password":"123456"
}

### POST request to login user
POST http://localhost:8000/api/auth/login/
content-type: application/json

{
  "username": "Valeria",
  "password": "123456"
}

### GET request to get all objects
GET http://localhost:8000/api/objects/?page=0

### GET request to get total objects
GET http://localhost:8000/api/total_objects

### Request to GitHub API TEST
GET https://api.github.com/users/LeivSuaxy

### POST to insert an object
POST http://localhost:8000/api/insertproduct/
content-type: multipart/form-data

{
  "product": {
        "nombre": "pepe",
        "precio": 300,
        "stock": 30,
        "categoria": "Carro",
        "inventario": 1,
        "descripcion": "Carro de juguete",
        "imagen":
  }
}
###
GET http://localhost:8000/api/admin/messengers/
